apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-web
  labels:
    app: events-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-web
      ver: v1.0
  template:
    metadata:
      labels:
        app: events-web
        ver: v1.0
    spec:
      containers:
        - name: events-web
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SERVER
              value: "http://${API_LB_URL}:8082"

